# Generated by Django 5.1.5 on 2025-01-19 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0005_remove_osoba_data_dodania_remove_osoba_wlasciciel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateField(auto_now_add=True, default='2025-01-19'),
            preserve_default=False,
        ),
    ]
