# Generated by Django 5.1.2 on 2025-01-19 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0005_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[(1, 'Kobieta', 2, 'Męzczyzna', 3, 'Inna')], default=1),
        ),
    ]
