# Generated by Django 5.1.2 on 2025-01-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0006_alter_osoba_plec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='plec',
            field=models.IntegerField(choices=[('K', 'Kobieta'), ('M', 'Męzczyzna'), ('I', 'Inna')], default='M', max_length=1),
        ),
    ]
