# Generated by Django 5.1.5 on 2025-01-23 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0006_osoba_data_dodania'),
        ('folder_aplikacji', '0007_alter_osoba_plec'),
    ]

    operations = [
    ]
